### ISSUE TITLE
[BUG] 预览只存放在icloud上的视频出错

### ISSUE THREAD

**Issue by ManhonSzeto** [fluttercandies/flutter_wechat_assets_picker#197]
**Describe the bug (描述)**
iOS下，选取存放在icloud上的视频，视频下载完成后无法预览且有错误提示
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Asset is not an AVURLAsset which does not include a media url., null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      _VideoPageBuilderState.initializeVideoPlayerController (package:wechat_assets_picker/src/widget/builder/video_page_builder.dart:74:25)
<asynchronous suspension>
```

关闭再重新打开该视频就恢复正常

**How to reproduce (如何复现)**
随便选取一个不在本地只在icloud的视频即可复现

**Expected behavior (期望行为)**
bug需要如何修复或可自行在哪部分修改？

**Device information (设备信息)**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS14.7.1]
 - Package Version: [e.g. 6.1.0]
 - Flutter Version: [e.g. v2.2.3]

**Comment by AlexV525** [comment]
试下将下面的内容替换 `lib/src/widget/builder/video_page_builder.dart` 是否解决了问题。

<details>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

import '../../constants/constants.dart';
import '../scale_text.dart';
import 'locally_available_builder.dart';

class VideoPageBuilder extends StatefulWidget {
  const VideoPageBuilder({
    Key? key,
    required this.asset,
    required this.delegate,
    this.hasOnlyOneVideoAndMoment = false,
  }) : super(key: key);

  /// Asset currently displayed.
  /// 展示的资源
  final AssetEntity asset;

  final AssetPickerViewerBuilderDelegate<AssetEntity, AssetPathEntity> delegate;

  /// Only previewing one video and with the [SpecialPickerType.wechatMoment].
  /// 是否处于 [SpecialPickerType.wechatMoment] 且只有一个视频
  final bool hasOnlyOneVideoAndMoment;

  @override
  _VideoPageBuilderState createState() => _VideoPageBuilderState();
}

class _VideoPageBuilderState extends State<VideoPageBuilder> {
  /// Controller for the video player.
  /// 视频播放的控制器
  late final VideoPlayerController _controller;

  /// Whether the controller has initialized.
  /// 控制器是否已初始化
  bool hasLoaded = false;

  /// Whether there's any error when initialize the video controller.
  /// 初始化视频控制器时是否发生错误
  bool hasErrorWhenInitializing = false;

  /// Whether the player is playing.
  /// 播放器是否在播放
  final ValueNotifier<bool> isPlaying = ValueNotifier<bool>(false);

  /// Whether the controller is playing.
  /// 播放控制器是否在播放
  bool get isControllerPlaying => _controller.value.isPlaying;

  bool _isInitializing = false;
  bool _isLocallyAvailable = false;

  @override
  void dispose() {
    /// Remove listener from the controller and dispose it when widget dispose.
    /// 部件销毁时移除控制器的监听并销毁控制器。
    _controller.removeListener(videoPlayerListener);
    _controller.pause();
    _controller.dispose();
    super.dispose();
  }

  /// Get media url from the asset, then initialize the controller and add with a listener.
  /// 从资源获取媒体url后初始化，并添加监听。
  Future<void> initializeVideoPlayerController() async {
    final String? url = await widget.asset.getMediaUrl();
    if (url == null) {
      hasErrorWhenInitializing = true;
      if (mounted) {
        setState(() {});
      }
      return;
    }
    _controller = VideoPlayerController.network(Uri.parse(url).toString());
    try {
      await _controller.initialize();
      hasLoaded = true;
      _controller
        ..addListener(videoPlayerListener)
        ..setLooping(widget.hasOnlyOneVideoAndMoment);
      if (widget.hasOnlyOneVideoAndMoment) {
        _controller.play();
      }
    } catch (e) {
      realDebugPrint('Error when initialize video controller: $e');
      hasErrorWhenInitializing = true;
    } finally {
      if (mounted) {
        setState(() {});
      }
    }
  }

  /// Listener for the video player.
  /// 播放器的监听方法
  void videoPlayerListener() {
    if (isControllerPlaying != isPlaying.value) {
      isPlaying.value = isControllerPlaying;
    }
  }

  /// Callback for the play button.
  /// 播放按钮的回调
  ///
  /// Normally it only switches play state for the player. If the video reaches the end,
  /// then click the button will make the video replay.
  /// 一般来说按钮只切换播放暂停。当视频播放结束时，点击按钮将从头开始播放。
  Future<void> playButtonCallback() async {
    if (isPlaying.value) {
      _controller.pause();
    } else {
      if (widget.delegate.isDisplayingDetail.value) {
        widget.delegate.switchDisplayingDetail(value: false);
      }
      if (_controller.value.duration == _controller.value.position) {
        _controller
          ..seekTo(Duration.zero)
          ..play();
      } else {
        _controller.play();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return LocallyAvailableBuilder(
      asset: widget.asset,
      builder: (BuildContext context, AssetEntity asset) {
        if (hasErrorWhenInitializing) {
          return Center(child: ScaleText(Constants.textDelegate.loadFailed));
        }
        if (!hasLoaded) {
          return const SizedBox.shrink();
        }
        if (_isLocallyAvailable && !_isInitializing) {
          _isInitializing = true;
          _isLocallyAvailable = true;
          initializeVideoPlayerController().then((_) {
            if (mounted) {
              setState(() {});
            }
          });
        }
        return Stack(
          fit: StackFit.expand,
          children: <Widget>[
            Positioned.fill(
              child: Center(
                child: AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                ),
              ),
            ),
            if (!widget.hasOnlyOneVideoAndMoment)
              ValueListenableBuilder<bool>(
                valueListenable: isPlaying,
                builder: (_, bool value, __) => GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: value
                      ? playButtonCallback
                      : widget.delegate.switchDisplayingDetail,
                  child: Center(
                    child: AnimatedOpacity(
                      duration: kThemeAnimationDuration,
                      opacity: value ? 0.0 : 1.0,
                      child: GestureDetector(
                        onTap: playButtonCallback,
                        child: DecoratedBox(
                          decoration: const BoxDecoration(
                            boxShadow: <BoxShadow>[
                              BoxShadow(color: Colors.black12)
                            ],
                            shape: BoxShape.circle,
                          ),
                          child: Icon(
                            value
                                ? Icons.pause_circle_outline
                                : Icons.play_circle_filled,
                            size: 70.0,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
          ],
        );
      },
    );
  }
}
```
</details>

**Comment by ManhonSzeto** [comment]
> 试下将下面的内容替换 `lib/src/widget/builder/video_page_builder.dart` 是否解决了问题。

这个修改之后，报错事没有了，但是从icloud下载完成之后，是空白内容的，而且返回再进去，一样是空白的，修改之前，返回再进去是可以正常预览的

**Comment by ManhonSzeto** [comment]
另外返回之后会报错，如下：
======== Exception caught by widgets library =======================================================
The following LateError was thrown while finalizing the widget tree:
LateInitializationError: Field '_controller@1593028584' has not been initialized.

When the exception was thrown, this was the stack: 
#0      _VideoPageBuilderState._controller (package:wechat_assets_picker/src/widget/builder/video_page_builder.dart)
#1      _VideoPageBuilderState.dispose (package:wechat_assets_picker/src/widget/builder/video_page_builder.dart:58:5)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
...
====================================================================================================

**Comment by AlexV525** [comment]
接着改，替换相关部分。

<details>

```dart

  @override
  Widget build(BuildContext context) {
    return LocallyAvailableBuilder(
      asset: widget.asset,
      builder: (BuildContext context, AssetEntity asset) {
        if (hasErrorWhenInitializing) {
          return Center(child: ScaleText(Constants.textDelegate.loadFailed));
        }
        if (!_isLocallyAvailable && !_isInitializing) {
          _isInitializing = true;
          _isLocallyAvailable = true;
          initializeVideoPlayerController().then((_) {
            if (mounted) {
              setState(() {});
            }
          });
        }
        if (!hasLoaded) {
          return const SizedBox.shrink();
        }
```
</details>

**Comment by ManhonSzeto** [comment]
可以了，暂时目测没有问题了，谢谢
另外问一个问题，ios在使用了icloud的情况下，加载相册列表很慢，但是不像android加载相册列表的时候有一个loading的动画，这个是可以自己定制，还是需要在哪修改？

**Comment by AlexV525** [comment]
UI 部分请查看 Delegate 源码。
