### ISSUE TITLE
[BUG] App crashes with fatal exception when trying to pick assets 

### ISSUE THREAD

**Issue by Anan-Saadi** [fluttercandies/flutter_wechat_assets_picker#256]
**Describe the bug**
App crashes when trying to pick assets on a Huawei P20 device

**How to reproduce**

1. Define a method called `getAssets()`:
```
  Future<List<AssetEntity>> getAssets() async {
    return await AssetPicker.pickAssets(context,
        maxAssets: 2,
        requestType: RequestType.common,
        textDelegate: EnglishTextDelegate());
  }
```
2. call `getAssets()` with a button: 
``` 
List<AssetEntity> assets;

IconButton(
      key: ValueKey(1),
      icon: Icon(
        Icons.photo,
        color: theme().mainColors(),
      ),
      onPressed: () async {
        try {
          global.assets = await getAssets();
        }catch(e){
          printError("error while picking images" + e);
        }
        },
    );
```
**Error log** 
<details><summary>CLICK ME</summary>
<p>

```
 I/QarthLog(14686): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(14686): [PatchStore] create disable file for com.Example.Test uid is 10316
E/AndroidRuntime(14686): FATAL EXCEPTION: pool-11-thread-2
E/AndroidRuntime(14686): Process: com.Example.Test, PID: 14686
E/AndroidRuntime(14686): java.lang.Error: java.io.FileNotFoundException: /storage/emulated/0/Pictures/JPEG_20211217_090449_6462321107414526769.jpg: open failed: EACCES (Permission denied)
E/AndroidRuntime(14686): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
E/AndroidRuntime(14686): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(14686): 	at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(14686): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Pictures/JPEG_20211217_090449_6462321107414526769.jpg: open failed: EACCES (Permission denied)
E/AndroidRuntime(14686): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/AndroidRuntime(14686): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
E/AndroidRuntime(14686): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
E/AndroidRuntime(14686): 	at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5289)
E/AndroidRuntime(14686): 	at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3952)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:241)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetFromGalleryIdRange(AndroidQDBUtils.kt:209)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.PhotoManager.getAssetListWithRange(PhotoManager.kt:88)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke(PhotoManagerPlugin.kt:279)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke(PhotoManagerPlugin.kt:272)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.$r8$lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/AndroidRuntime(14686): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(14686): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(14686): 	... 2 more
E/AndroidRuntime(14686): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E/AndroidRuntime(14686): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime(14686): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(14686): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/AndroidRuntime(14686): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(14686): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8046)
E/AndroidRuntime(14686): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/AndroidRuntime(14686): 	... 15 more
I/Process (14686): Sending signal. PID: 14686 SIG: 9
```
</p>
</details>

**Version information**

- Device: Huawei P20
- OS: Android 10
- Package Version: 7.0.0-dev.2 
- Flutter Version:  2.9.0-1.0.pre.129 • channel master

**Additional context**
I first thought that I need to request legacy storage permission or something like that, but `image_picker` has previously worked with same device with same permissions, which is why I believe the issue is in the package.

I have also tested the exact same code with:
Galaxy Note 20 (Android 12)
Galaxy S9 (Android 10)
Google pixel 3 emulator (Android 10)
and they all work as intended

**Comment by AlexV525** [comment]
Can you confirm that your app is using the legacy storage? Also, which version of `photo_manager` you've depended on?
