### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by Insist-g** [fluttercandies/flutter_wechat_assets_picker#495]
使用common方式，选择视频控制台出现下面的错误

```console
E/PhotoManager( 2374): setDataSource failed: status = 0xFFFFFFEA
D/skia    ( 2374): --- SkAndroidCodec::NewFromStream returned null
D/skia    ( 2374): --- SkAndroidCodec::NewFromStream returned null
V/BitmapFactoryEx( 2374): nativeDecodeFileDescriptorEx
D/skia    ( 2374): --- SkAndroidCodec::NewFromStream returned null
V/BitmapFactoryEx( 2374): nativeDecodeFileDescriptorEx
D/skia    ( 2374): --- SkAndroidCodec::NewFromStream returned null
W/Glide   ( 2374): Load failed for [content://media/external/video/media/346865] with dimensions [200x200]
W/Glide   ( 2374): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
W/Glide   ( 2374): There were 2 root causes:
W/Glide   ( 2374): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
W/Glide   ( 2374): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
W/Glide   ( 2374):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 2374):   Cause (1 of 4): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AutoCloseInputStream->Bitmap->Bitmap}, LOCAL
W/Glide   ( 2374):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->Bitmap->Bitmap}
W/Glide   ( 2374):   Cause (2 of 4): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptorInner->Bitmap->Bitmap}, LOCAL
W/Glide   ( 2374): There was 1 root cause:
W/Glide   ( 2374): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
W/Glide   ( 2374):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 2374):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptorInner->Bitmap->Bitmap}
W/Glide   ( 2374): There was 1 root cause:
W/Glide   ( 2374): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
W/Glide   ( 2374):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 2374):       Cause (1 of 1): class java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
W/Glide   ( 2374):   Cause (3 of 4): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetFileDescriptor->Bitmap->Bitmap}, LOCAL
W/Glide   ( 2374): There was 1 root cause:
W/Glide   ( 2374): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
W/Glide   ( 2374):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 2374):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetFileDescriptor->Bitmap->Bitmap}
W/Glide   ( 2374): There was 1 root cause:
W/Glide   ( 2374): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
W/Glide   ( 2374):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 2374):       Cause (1 of 1): class java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
W/Glide   ( 2374):   Cause (4 of 4): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{HierarchicalUri->Bitmap->Bitmap}, LOCAL
W/Glide   ( 2374):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{HierarchicalUri->Bitmap->Bitmap}
I/Glide   ( 2374): Root cause (1 of 2)
I/Glide   ( 2374): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
I/Glide   ( 2374): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
I/Glide   ( 2374): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:139)
I/Glide   ( 2374): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initializeRetriever(VideoDecoder.java:497)
I/Glide   ( 2374): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initializeRetriever(VideoDecoder.java:492)
I/Glide   ( 2374): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:191)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:539)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:503)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:489)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:434)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:399)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:211)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:101)
I/Glide   ( 2374): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:442)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:399)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:211)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:101)
I/Glide   ( 2374): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
I/Glide   ( 2374): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
I/Glide   ( 2374): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
I/Glide   ( 2374): 	at java.lang.Thread.run(Thread.java:784)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)
I/Glide   ( 2374): Root cause (2 of 2)
I/Glide   ( 2374): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
I/Glide   ( 2374): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
I/Glide   ( 2374): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$AssetFileDescriptorInitializer.initializeRetriever(VideoDecoder.java:481)
I/Glide   ( 2374): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$AssetFileDescriptorInitializer.initializeRetriever(VideoDecoder.java:476)
I/Glide   ( 2374): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:191)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:539)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:503)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:489)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:434)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:399)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:211)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:101)
I/Glide   ( 2374): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:442)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:399)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:211)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:101)
I/Glide   ( 2374): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:442)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:399)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:211)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:101)
I/Glide   ( 2374): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
I/Glide   ( 2374): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
I/Glide   ( 2374): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
I/Glide   ( 2374): 	at java.lang.Thread.run(Thread.java:784)
I/Glide   ( 2374): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)

======== Exception caught by photo_manager =========================================================
The following PlatformException was thrown:
PlatformException(Thumbnail request error, java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There were 2 root causes:
java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
 call GlideException#logRootCauses(String) for more detail, null, null)

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      AssetEntityImageProvider._loadAsync (package:photo_manager/src/internal/image_provider.dart:123:16)
<asynchronous suspension>
====================================================================================================
```

**Version information**

- Device: huawei 荣耀8X
- Package Version: (version: 8.6.3)
- Flutter Version: 3.10.6

**Comment by kangtian** [comment]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/wechat_assets_picker-8.8.0/lib/src/widget/builder/asset_entity_grid_item_builder.dart:19:9: Error: Type 'AssetEntityImageProvider' not found.

**Comment by AlexV525** [comment]
加载某个资源出现错误很正常，建议针对某个资源排查问题。
