### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by Jinxishihenian** [fluttercandies/flutter_wechat_assets_picker#530]
**Describe the bug**

When I currently select an image using this component, the authorization screen pops up and the application crashes when I deny access.
**How to reproduce**

                         // Take pictures and upload them.
                              final AssetEntity? entity =
                                  await CameraPicker.pickFromCamera(
                                context,
                                pickerConfig: const CameraPickerConfig(
                                  enableRecording: false,
                                  onlyEnableRecording: false,
                                ),
                              );

1. Invoke the shooting method.
2. The authorization pop-up window is displayed.
3. Click Reject, and the application crashes.

**Expected behavior**

Disable access to the camera or album, and prompt no permission
**Screenshots (If contains)**

**Version information**

- Device: [nova 5 Pro]
- OS: []
- Package Version: [^8.8.0]
- Flutter Version: [3.16.3]

**Additional context**

     When I refused to grant permission, I didn't print logs
     ```
     D/RtgSchedIpcFile( 8935): setCommandByIoctl failed ret:-1, cmdid:22, errno:103
E/flutter ( 8935): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(CameraAccessDenied, Camera access permission was denied.)
E/flutter ( 8935): #0      AndroidCamera.createCamera (package:camera_android/src/android_camera.dart:112:7)
E/flutter ( 8935): <asynchronous suspension>
E/flutter ( 8935): #1      CameraController._initializeWithDescription (package:camera/src/camera_controller.dart:316:19)
E/flutter ( 8935): <asynchronous suspension>
E/flutter ( 8935): #2      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:395:9)
E/flutter ( 8935): <asynchronous suspension>
E/flutter ( 8935): 
    ```

**Comment by AlexV525** [comment]
Crashes? Please provide a screen record.

**Comment by Jinxishihenian** [comment]
log information
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/44466363/ba05a6e4-58ee-4b5c-a2c6-574e39c46c87)

![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/44466363/6f6c7c85-16f3-4d63-aed2-c5735e4b58ca)
![image](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/44466363/2ced9a7e-1f0f-4b71-a16c-2d3ae35f1552)

Screen information

https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/44466363/2f7c6db5-198e-4f73-938b-e7de8949a480
