### ISSUE TITLE
[BUG] Permission state error with PermissionState.denied on Android 13

### ISSUE THREAD

**Issue by MostafaTawfik7** [fluttercandies/flutter_wechat_assets_picker#551]
**Describe the bug**

The issue is only related to Android 13

`E/flutter ( 5378): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Permission state error with PermissionState.denied.
E/flutter ( 5378): #0      AssetPickerDelegate.permissionCheck (package:wechat_assets_picker/src/delegates/asset_picker_delegate.dart:39:7)
E/flutter ( 5378): <asynchronous suspension>
E/flutter ( 5378): #1      AssetPickerDelegate.pickAssets (package:wechat_assets_picker/src/delegates/asset_picker_delegate.dart:71:32)
E/flutter ( 5378): <asynchronous suspension>
E/flutter ( 5378): #2      AssignmentCubit.getImageFromMyGallery (package:pxora/features/assignements/presentation/controllers/cubit/assignment_cubit.dart:434:22)`

The issue is only related to Android 13 and I've tried adding a bunch of permissions as well in the android manifest file that are related to android 13
`   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

**Version information**

- Device: [e.g.  every android 13 device]
- OS: [e.g. Android 13]
- Package Version: [e.g. ^9.0.0-dev.2]
- Flutter Version: [e.g. v3.16.4]

**Comment by AlexV525** [comment]
You'll need to follow the instruction and find out what is the difference between your app and the example.
